### ISSUE TITLE
There already is evm

### ISSUE THREAD

**Issue by Fuco1** [argentum47/everm#1]
Are there any significant differences here?

https://github.com/rejeep/evm

**Comment by ikouchiha47** [comment]
Not really, though, I wasn't aware of this, but one has to have a ruby dependency, I wanted to eliminate that.
But again my one doesn't quite work right, because ya know compiling source on all kinds of distribution isn't easy. (unless there is a trick and I don't know it), fedora and some os have their own patches, I am looking for a way to make this perfect. 

I made this project, so that I can solely depend on the build tools rather than having to depend on ruby every time. Its emacs not rubymacs.
